// GET
export const EDUCATIONS_REQUEST = `EDUCATIONS_REQUEST`;
export const EDUCATIONS_SUCCESS = `EDUCATIONS_SUCCESS`;
export const EDUCATIONS_FAIL = `EDUCATIONS_FAIL`;

// CREATE
export const EDUCATIONS_CREATE_REQUEST = `EDUCATIONS_CREATE_REQUEST`;
export const EDUCATIONS_CREATE_SUCCESS = `EDUCATIONS_CREATE_SUCCESS`;
export const EDUCATIONS_CREATE_FAIL = `EDUCATIONS_CREATE_FAIL`;

// UPDATE
export const EDUCATIONS_UPDATE_REQUEST = `EDUCATIONS_UPDATE_REQUEST`;
export const EDUCATIONS_UPDATE_SUCCESS = `EDUCATIONS_UPDATE_SUCCESS`;
export const EDUCATIONS_UPDATE_FAIL = `EDUCATIONS_UPDATE_FAIL`;

// DELETE
export const EDUCATIONS_DELETE_REQUEST = `EDUCATIONS_DELETE_REQUEST`;
export const EDUCATIONS_DELETE_SUCCESS = `EDUCATIONS_DELETE_SUCCESS`;
export const EDUCATIONS_DELETE_FAIL = `EDUCATIONS_DELETE_FAIL`;
