// GET
export const EXPERIENCES_REQUEST = `EXPERIENCES_REQUEST`;
export const EXPERIENCES_SUCCESS = `EXPERIENCES_SUCCESS`;
export const EXPERIENCES_FAIL = `EXPERIENCES_FAIL`;

// CREATE
export const EXPERIENCES_CREATE_REQUEST = `EXPERIENCES_CREATE_REQUEST`;
export const EXPERIENCES_CREATE_SUCCESS = `EXPERIENCES_CREATE_SUCCESS`;
export const EXPERIENCES_CREATE_FAIL = `EXPERIENCES_CREATE_FAIL`;

// UPDATE
export const EXPERIENCES_UPDATE_REQUEST = `EXPERIENCES_UPDATE_REQUEST`;
export const EXPERIENCES_UPDATE_SUCCESS = `EXPERIENCES_UPDATE_SUCCESS`;
export const EXPERIENCES_UPDATE_FAIL = `EXPERIENCES_UPDATE_FAIL`;

// DELETE
export const EXPERIENCES_DELETE_REQUEST = `EXPERIENCES_DELETE_REQUEST`;
export const EXPERIENCES_DELETE_SUCCESS = `EXPERIENCES_DELETE_SUCCESS`;
export const EXPERIENCES_DELETE_FAIL = `EXPERIENCES_DELETE_FAIL`;
