// FETCH FRIENDS
export const FETCHING_FRIENDS_REQUEST = `FETCHING_FRIENDS_REQUEST`;
export const FETCHING_FRIENDS_SUCCESS = `FETCHING_FRIENDS_SUCCESS`;
export const FETCHING_FRIENDS_FAIL = `FETCHING_FRIENDS_FAIL`;

// MAKE FRIEND
export const MAKE_FRIEND_REQUEST = `MAKE_FRIEND_REQUEST`;
export const MAKE_FRIEND_SUCCESS = `MAKE_FRIEND_SUCCESS`;
export const MAKE_FRIEND_FAIL = `MAKE_FRIEND_FAIL`;

// UNMAKE FRIEND
export const UNFRIEND_REQUEST = `UNFRIEND_REQUEST`;
export const UNFRIEND_SUCCESS = `UNFRIEND_SUCCESS`;
export const UNFRIEND_FAIL = `UNFRIEND_FAIL`;
