// FETCH OTHERS
export const FETCHING_OTHERS_REQUEST = `FETCHING_OTHERS_REQUEST`;
export const FETCHING_OTHERS_SUCCESS = `FETCHING_OTHERS_SUCCESS`;
export const FETCHING_OTHERS_FAIL = `FETCHING_OTHERS_FAIL`;
